server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  mvc:
    format:
      date-time: iso
  messages:
    basename: messages

logging:
  level:
    org:
      springframework: info